const Data = [
    {
        id:1,
        img:'https://cdn.w600.comps.canstockphoto.com/young-man-with-big-black-leather-bag-stock-photography_csp46786700.jpg',
        title:'The Brown Metro Movers',
        price:4899,
        total_price: 8999,
        discount: 50,
    },
    {
        id:2,
        img:'https://cdn.w600.comps.canstockphoto.com/young-man-with-big-black-leather-bag-stock-photography_csp46786700.jpg',
        title:'The Brown Metro Movers',
        price:4899,
        total_price: 8999,
        discount: 50,
    },
    {
        id:3,
        img:'https://cdn.w600.comps.canstockphoto.com/young-man-with-big-black-leather-bag-stock-photography_csp46786700.jpg',
        title:'The Brown Metro Movers',
        price:4899,
        total_price: 8999,
        discount: 50,
    },
    {
        id:4,
        img:'https://cdn.w600.comps.canstockphoto.com/young-man-with-big-black-leather-bag-stock-photography_csp46786700.jpg',
        title:'The Brown Metro Movers',
        price:4899,
        total_price: 8999,
        discount: 50,
    },
    {
        id:5,
        img:'https://cdn.w600.comps.canstockphoto.com/young-man-with-big-black-leather-bag-stock-photography_csp46786700.jpg',
        title:'The Brown Metro Movers',
        price:4899,
        total_price: 8999,
        discount: 50,
    },
    {
        id:6,
        img:'https://cdn.w600.comps.canstockphoto.com/young-man-with-big-black-leather-bag-stock-photography_csp46786700.jpg',
        title:'The Brown Metro Movers',
        price:4899,
        total_price: 8999,
        discount: 50,
    },
    {
        id:7,
        img:'https://cdn.w600.comps.canstockphoto.com/young-man-with-big-black-leather-bag-stock-photography_csp46786700.jpg',
        title:'The Brown Metro Movers',
        price:4899,
        total_price: 8999,
        discount: 50,
    },
    {
        id:8,
        img:'https://cdn.w600.comps.canstockphoto.com/young-man-with-big-black-leather-bag-stock-photography_csp46786700.jpg',
        title:'The Brown Metro Movers',
        price:4899,
        total_price: 8999,
        discount: 50,
    },
    {
        id:9,
        img:'https://cdn.w600.comps.canstockphoto.com/young-man-with-big-black-leather-bag-stock-photography_csp46786700.jpg',
        title:'The Brown Metro Movers',
        price:4899,
        total_price: 8999,
        discount: 50,
    },
    {
        id:10,
        img:'https://cdn.w600.comps.canstockphoto.com/young-man-with-big-black-leather-bag-stock-photography_csp46786700.jpg',
        title:'The Brown Metro Movers',
        price:4899,
        total_price: 8999,
        discount: 50,
    },
    {
        id:11,
        img:'https://cdn.w600.comps.canstockphoto.com/young-man-with-big-black-leather-bag-stock-photography_csp46786700.jpg',
        title:'The Brown Metro Movers',
        price:4899,
        total_price: 8999,
        discount: 50,
    },
    {
        id:12,
        img:'https://cdn.w600.comps.canstockphoto.com/young-man-with-big-black-leather-bag-stock-photography_csp46786700.jpg',
        title:'The Brown Metro Movers',
        price:4899,
        total_price: 8999,
        discount: 50,
    },
  
]
export default Data;